//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Item_Type> Item_Type { get; set; }
        public virtual DbSet<ItemType> ItemType { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Provider_Item> Provider_Item { get; set; }
        public virtual DbSet<Quest> Quest { get; set; }
        public virtual DbSet<Quest_Item> Quest_Item { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ShopQuest> ShopQuest { get; set; }
        public virtual DbSet<ShopQuest_item> ShopQuest_item { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<Supply_Item> Supply_Item { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<WriteOff> WriteOff { get; set; }
    }
}
