//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopQuest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopQuest()
        {
            this.ShopQuest_item = new HashSet<ShopQuest_item>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Id_Provider { get; set; }
        public int State { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopQuest_item> ShopQuest_item { get; set; }
    }
}
