//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public int Id { get; set; }
        public int Id_User { get; set; }
        public int Id_Role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
